#!/usr/bin/env python3
"""Build or verify deterministic lighthouse PDFs and source-truth oracles."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from common.atomic import atomic_write
from common.lighthouse import (
    LighthouseError,
    SyntheticFixture,
    build_synthetic_pdf,
    expected_json_bytes,
    load_fixture,
)


_SLUG = re.compile(r"[a-z][a-z0-9_]{0,63}\Z")


class FixtureDriftError(LighthouseError):
    """Raised in check mode when generated bytes differ or are missing."""


@dataclass(frozen=True)
class BuildResult:
    pdf_path: Path
    expected_path: Path
    checked: bool


def _contained_demo_dir(demos_root: Path, slug: str) -> Path:
    if not _SLUG.fullmatch(slug):
        raise LighthouseError("demo name must be a lowercase underscore slug")
    try:
        root = demos_root.resolve(strict=True)
        candidate = demos_root / slug
        if candidate.is_symlink() or not candidate.is_dir():
            raise LighthouseError("selected demo must be a regular directory")
        resolved = candidate.resolve(strict=True)
        resolved.relative_to(root)
    except LighthouseError:
        raise
    except (OSError, ValueError):
        raise LighthouseError("selected demo escapes the demos directory") from None
    return resolved


def _safe_destination(demo_dir: Path, relative_path: PurePosixPath) -> Path:
    destination = demo_dir.joinpath(*relative_path.parts)
    try:
        demo_root = demo_dir.resolve(strict=True)
        destination.parent.resolve(strict=False).relative_to(demo_root)
    except (OSError, ValueError):
        raise LighthouseError("generated destination escapes the selected demo") from None

    cursor = demo_root
    for part in relative_path.parts[:-1]:
        cursor = cursor / part
        if cursor.exists() and cursor.is_symlink():
            raise LighthouseError("generated destination contains a symbolic link")
        if cursor.exists() and not cursor.is_dir():
            raise LighthouseError("generated destination parent is not a directory")
    if destination.is_symlink():
        raise LighthouseError("generated destination must not be a symbolic link")
    if destination.exists() and not destination.is_file():
        raise LighthouseError("generated destination must be a regular file")
    return destination


def _check_bytes(path: Path, expected: bytes) -> None:
    try:
        if path.is_symlink() or not path.is_file():
            raise FixtureDriftError(f"generated artifact is missing: {path}")
        actual = path.read_bytes()
    except FixtureDriftError:
        raise
    except OSError:
        raise LighthouseError("could not safely read generated artifact") from None
    if actual != expected:
        raise FixtureDriftError(f"generated artifact is stale: {path}")


def build_demo_fixture(
    demo_dir: Path,
    *,
    check: bool = False,
    expected_slug: str | None = None,
) -> BuildResult:
    """Build one fixture PDF and expected.json, or verify exact bytes."""

    if demo_dir.is_symlink() or not demo_dir.is_dir():
        raise LighthouseError("demo directory must be a regular directory")
    slug = expected_slug or demo_dir.name
    if not _SLUG.fullmatch(slug):
        raise LighthouseError("demo name must be a lowercase underscore slug")
    fixture = load_fixture(demo_dir / "fixture.json", expected_slug=slug)
    if not isinstance(fixture, SyntheticFixture):
        raise LighthouseError(
            "fixture builder accepts only version-1 synthetic fixtures and will "
            "not overwrite an authentic public-form source"
        )
    pdf_path = _safe_destination(demo_dir, fixture.filename)
    expected_path = _safe_destination(demo_dir, PurePosixPath("expected.json"))
    pdf_payload = build_synthetic_pdf(fixture)
    expected_payload = expected_json_bytes(fixture)

    if check:
        drift: list[str] = []
        for path, payload in (
            (pdf_path, pdf_payload),
            (expected_path, expected_payload),
        ):
            try:
                _check_bytes(path, payload)
            except FixtureDriftError as error:
                drift.append(str(error))
        if drift:
            raise FixtureDriftError("\n".join(drift))
    else:
        atomic_write(pdf_path, pdf_payload)
        atomic_write(expected_path, expected_payload)

    return BuildResult(
        pdf_path=pdf_path,
        expected_path=expected_path,
        checked=check,
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a lighthouse demo's deterministic synthetic PDF and "
            "source-derived expected.json."
        )
    )
    parser.add_argument("demo", help="Demo directory name under demos/")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify committed artifacts byte-for-byte without writing.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        demo_dir = _contained_demo_dir(REPO_ROOT / "demos", args.demo)
        result = build_demo_fixture(
            demo_dir,
            check=args.check,
            expected_slug=args.demo,
        )
    except FixtureDriftError as error:
        print(str(error), file=sys.stderr)
        return 1
    except LighthouseError as error:
        print(f"fixture build failed: {error}", file=sys.stderr)
        return 2

    action = "Verified" if result.checked else "Built"
    print(f"{action} {result.pdf_path.relative_to(REPO_ROOT)}")
    print(f"{action} {result.expected_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
